### ISSUE TITLE
Possibility to add custom ADR algorithm plugin

### ISSUE THREAD

**Issue by thomasSensade** [OS2iot/OS2IoT-frontend#103]
Hi,

The default ADR algorithm is too agressive in turning down the TX power, for our sensors, due to the environment in which they are installed.

Our sensors (parking sensors) are installed in the ground, with vehicles parking over them from time to time, and whenever a vehicle parks over a sensor, the signal gets significantly attenuated. 

In periods with no car on top of a sensor the signal looks good, and so the default ADR algorithm turns down the TX power (often -10 to -14 dB), which means that alot of our packages gets lost as soon as a car parks over the sensor

Because of this, I would like to request a possibility to specify a custom ADR algorithm, which is better suited for a particular sensor device. 
I have already discussed this with @GufCab 

Best Regards,
Thomas Olsen
Sensade ApS

**Comment by ALionTiger** [comment]
Hi Thomas, 

The installation margin that is used in the ADR engine is set to 10 dB! At the moment i see three possible quick-fix's that could address your issue now.

1. We could increase the installation_margin in the configuration file of the chirpstack network server, however this would result in a lower data-rate off all applications, but positively decreasing the package loss you say that you are experiencing.
2. We can make another service-profile for your sensors/applications that narrows the range of the data-rate, instead of it always being from 0 to 5. I am not sure how positive the outcome would be, but it is used in the ADR engine.
3. You disable ADR on all of your devices.

**Comment by ramogens** [comment]
This feature has been implemented with release 1.3.0: https://github.com/OS2iot/OS2IoT-frontend/releases/tag/v.1.3.0
