### ISSUE TITLE
Possibility to add lorawan downlink frames to datatarget

### ISSUE THREAD

**Issue by thomasSensade** [OS2iot/OS2IoT-frontend#105]
Hi,

Currently only uplink packages are sent to the specified datatargets. It would be very beneficial, for debugging purposes, if the downlink frames could also be sent to datatargets. This would enable us to keep track of what commands are sent to our devices.

Best Regards,
Thomas Olsen
Sensade ApS

**Comment by ramogens** [comment]
Hi @thomasSensade 
Thanks for this feature request. It's been added to our Jira backlog for consideration: https://os2web.atlassian.net/browse/IOT-1385 
Best,
Mogens
Product coordinator, OS2iot

**Comment by ramogens** [comment]
Hi @thomasSensade 
Sorry for our late reaction to your issue. The OS2iot coordination group have not seen this need in any situations and don't expect much need from this, since most supplier will handle downlinks themselves using the OS2iot API. So we have decided not to include this feature.
Best,
Mogens
Product coordinator, OS2iot
